import { Inter } from 'next/font/google';
import Header from '../components/header';
import StoreProvider from '../components/storeProvider';
import './globals.css';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Home Run Verdi',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${inter.className} flex flex-col justify-center items-center content-stretch`}>
                <Header />
                <main className='flex flex-col items-center justify-start min-h-[calc(100dvh)] w-full max-w-4xl flex-1'>
                    <StoreProvider>{children}</StoreProvider>
                </main>
            </body>
        </html>
    );
}
