import { Inter } from 'next/font/google';
import Header from '../components/header';
import Subheader from '../components/subheader';
import StoreProvider from '../components/storeProvider';
import './globals.css';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Home Run Verdi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </head>
      <body
        className={`${inter.className} flex flex-col justify-center items-center content-stretch font-medium`}>
        <Header />
        <main className='flex flex-col items-center justify-start min-h-[calc(100dvh)] w-full flex-1'>
          <StoreProvider>
            <Subheader />
            <div className='w-full max-w-4xl p-4'>{children}</div>
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
